name: strop_app_v2
description: "strop, Comunicacion para constructoras"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  go_router: ^16.2.4
  get_it: ^8.2.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  image_picker: ^1.2.0
  lottie: ^3.3.2
  url_strategy: ^0.3.0
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1
  drift_dev: ^2.28.3
  build_runner: ^2.9.0
  connectivity_plus: ^7.0.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - lib/assets/animations/login_animation.json

icons_launcher:
  image_path: 'lib\assets\icons\helmet.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true